import NotFound from "../components/elements/notfound";
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const FourOhFour: NextPage = () => {
    return (
      <div className={styles.container}>
        <Head>
          <title>MiladyCola</title>
          <meta
            content="Generated by @rainbow-me/create-rainbowkit"
            name="description"
          />
          <Link rel="shortcut icon" href="/" ></Link>
        </Head>
        <NotFound />
        </div>
    )
}

export default FourOhFour;